from __future__ import annotations

"""Deterministic eligibility rejection reason codes for shadow mode."""

from enum import Enum
from typing import FrozenSet


class EligibilityReasonCode(str, Enum):
    PROGRAM_IDENTITY_MISMATCH = "PROGRAM_IDENTITY_MISMATCH"
    HOST_ARCH_MISMATCH = "HOST_ARCH_MISMATCH"
    WINE_MAJOR_INCOMPATIBLE = "WINE_MAJOR_INCOMPATIBLE"
    REQUIRED_CAPABILITY_MISSING = "REQUIRED_CAPABILITY_MISSING"
    ACTIVE_HOST_CLASS_INVALIDATION = "ACTIVE_HOST_CLASS_INVALIDATION"
    ACTIVE_PROGRAM_INVALIDATION = "ACTIVE_PROGRAM_INVALIDATION"
    TRUST_STATE_SHADOW_ONLY = "TRUST_STATE_SHADOW_ONLY"
    VERIFICATION_BINDING_INCOMPATIBLE = "VERIFICATION_BINDING_INCOMPATIBLE"
    VERIFICATION_POLICY_ID_MISMATCH = "VERIFICATION_POLICY_ID_MISMATCH"
    VERIFICATION_POLICY_VERSION_INCOMPATIBLE = "VERIFICATION_POLICY_VERSION_INCOMPATIBLE"
    REQUIRED_CHECKS_MISMATCH = "REQUIRED_CHECKS_MISMATCH"
    VERIFIER_VERSION_INCOMPATIBLE = "VERIFIER_VERSION_INCOMPATIBLE"
    VERIFICATION_PHASE_MISMATCH = "VERIFICATION_PHASE_MISMATCH"
    VERIFICATION_POLICY_UNKNOWN = "VERIFICATION_POLICY_UNKNOWN"
    UNSUPPORTED_BRIDGE_FAMILY = "UNSUPPORTED_BRIDGE_FAMILY"
    ARTIFACT_CHECKSUM_MISSING = "ARTIFACT_CHECKSUM_MISSING"
    ARTIFACT_PROVENANCE_FAILURE = "ARTIFACT_PROVENANCE_FAILURE"
    MANIFEST_SCHEMA_UNSUPPORTED = "MANIFEST_SCHEMA_UNSUPPORTED"
    INVALID_LIFECYCLE_STATE = "INVALID_LIFECYCLE_STATE"
    RETIRED_PROFILE_DIAGNOSTIC_ONLY = "RETIRED_PROFILE_DIAGNOSTIC_ONLY"
    INVALIDATED_PROFILE_DIAGNOSTIC_ONLY = "INVALIDATED_PROFILE_DIAGNOSTIC_ONLY"
    OS_FAMILY_MISMATCH = "OS_FAMILY_MISMATCH"
    GPU_CLASS_MISMATCH = "GPU_CLASS_MISMATCH"


WINNER_BLOCKING_REASONS: FrozenSet[EligibilityReasonCode] = frozenset(
    {
        EligibilityReasonCode.PROGRAM_IDENTITY_MISMATCH,
        EligibilityReasonCode.HOST_ARCH_MISMATCH,
        EligibilityReasonCode.WINE_MAJOR_INCOMPATIBLE,
        EligibilityReasonCode.REQUIRED_CAPABILITY_MISSING,
        EligibilityReasonCode.ACTIVE_HOST_CLASS_INVALIDATION,
        EligibilityReasonCode.ACTIVE_PROGRAM_INVALIDATION,
        EligibilityReasonCode.VERIFICATION_BINDING_INCOMPATIBLE,
        EligibilityReasonCode.VERIFICATION_POLICY_ID_MISMATCH,
        EligibilityReasonCode.VERIFICATION_POLICY_VERSION_INCOMPATIBLE,
        EligibilityReasonCode.REQUIRED_CHECKS_MISMATCH,
        EligibilityReasonCode.VERIFIER_VERSION_INCOMPATIBLE,
        EligibilityReasonCode.VERIFICATION_PHASE_MISMATCH,
        EligibilityReasonCode.VERIFICATION_POLICY_UNKNOWN,
        EligibilityReasonCode.UNSUPPORTED_BRIDGE_FAMILY,
        EligibilityReasonCode.ARTIFACT_CHECKSUM_MISSING,
        EligibilityReasonCode.ARTIFACT_PROVENANCE_FAILURE,
        EligibilityReasonCode.MANIFEST_SCHEMA_UNSUPPORTED,
        EligibilityReasonCode.INVALID_LIFECYCLE_STATE,
        EligibilityReasonCode.RETIRED_PROFILE_DIAGNOSTIC_ONLY,
        EligibilityReasonCode.INVALIDATED_PROFILE_DIAGNOSTIC_ONLY,
    }
)

SHADOW_ONLY_TRUST_STATES: FrozenSet[str] = frozenset(
    {"imported", "manually_modified", "shadow_only"}
)

ACTIVE_REUSE_TRUST_STATES: FrozenSet[str] = frozenset(
    {"locally_verified", "reused_successfully"}
)

DIAGNOSTIC_ONLY_LIFECYCLE_STATES: FrozenSet[str] = frozenset(
    {"RETIRED", "INVALIDATED"}
)

WINNER_LIFECYCLE_STATES: FrozenSet[str] = frozenset({"VERIFIED"})
